/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PdfTranslatorRouteImport } from './routes/pdf-translator'
import { Route as PassportPhotoMakerRouteImport } from './routes/passport-photo-maker'
import { Route as JpgToWebpRouteImport } from './routes/jpg-to-webp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogDotrssDotxmlRouteImport } from './routes/blog[.]rss[.]xml'
import { Route as BackgroundRemoverRouteImport } from './routes/background-remover'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VsIndexRouteImport } from './routes/vs.index'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as AiPromptsIndexRouteImport } from './routes/ai-prompts.index'
import { Route as VsCompetitorRouteImport } from './routes/vs.$competitor'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AiPromptsSlugRouteImport } from './routes/ai-prompts.$slug'
import { Route as FrToolsSlugRouteImport } from './routes/fr.tools.$slug'
import { Route as EsToolsSlugRouteImport } from './routes/es.tools.$slug'
import { Route as ArToolsSlugRouteImport } from './routes/ar.tools.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfTranslatorRoute = PdfTranslatorRouteImport.update({
  id: '/pdf-translator',
  path: '/pdf-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportPhotoMakerRoute = PassportPhotoMakerRouteImport.update({
  id: '/passport-photo-maker',
  path: '/passport-photo-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToWebpRoute = JpgToWebpRouteImport.update({
  id: '/jpg-to-webp',
  path: '/jpg-to-webp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDotrssDotxmlRoute = BlogDotrssDotxmlRouteImport.update({
  id: '/blog.rss.xml',
  path: '/blog.rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRemoverRoute = BackgroundRemoverRouteImport.update({
  id: '/background-remover',
  path: '/background-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsIndexRoute = VsIndexRouteImport.update({
  id: '/vs/',
  path: '/vs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/ar/',
  path: '/ar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPromptsIndexRoute = AiPromptsIndexRouteImport.update({
  id: '/ai-prompts/',
  path: '/ai-prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsCompetitorRoute = VsCompetitorRouteImport.update({
  id: '/vs/$competitor',
  path: '/vs/$competitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPromptsSlugRoute = AiPromptsSlugRouteImport.update({
  id: '/ai-prompts/$slug',
  path: '/ai-prompts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrToolsSlugRoute = FrToolsSlugRouteImport.update({
  id: '/fr/tools/$slug',
  path: '/fr/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsToolsSlugRoute = EsToolsSlugRouteImport.update({
  id: '/es/tools/$slug',
  path: '/es/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArToolsSlugRoute = ArToolsSlugRouteImport.update({
  id: '/ar/tools/$slug',
  path: '/ar/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/blog.rss.xml': typeof BlogDotrssDotxmlRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/jpg-to-webp': typeof JpgToWebpRoute
  '/passport-photo-maker': typeof PassportPhotoMakerRoute
  '/pdf-translator': typeof PdfTranslatorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai-prompts/$slug': typeof AiPromptsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/ai-prompts/': typeof AiPromptsIndexRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/vs/': typeof VsIndexRoute
  '/ar/tools/$slug': typeof ArToolsSlugRoute
  '/es/tools/$slug': typeof EsToolsSlugRoute
  '/fr/tools/$slug': typeof FrToolsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/blog.rss.xml': typeof BlogDotrssDotxmlRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/jpg-to-webp': typeof JpgToWebpRoute
  '/passport-photo-maker': typeof PassportPhotoMakerRoute
  '/pdf-translator': typeof PdfTranslatorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai-prompts/$slug': typeof AiPromptsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/ai-prompts': typeof AiPromptsIndexRoute
  '/ar': typeof ArIndexRoute
  '/blog': typeof BlogIndexRoute
  '/es': typeof EsIndexRoute
  '/fr': typeof FrIndexRoute
  '/vs': typeof VsIndexRoute
  '/ar/tools/$slug': typeof ArToolsSlugRoute
  '/es/tools/$slug': typeof EsToolsSlugRoute
  '/fr/tools/$slug': typeof FrToolsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/blog.rss.xml': typeof BlogDotrssDotxmlRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/jpg-to-webp': typeof JpgToWebpRoute
  '/passport-photo-maker': typeof PassportPhotoMakerRoute
  '/pdf-translator': typeof PdfTranslatorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai-prompts/$slug': typeof AiPromptsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/ai-prompts/': typeof AiPromptsIndexRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/es/': typeof EsIndexRoute
  '/fr/': typeof FrIndexRoute
  '/vs/': typeof VsIndexRoute
  '/ar/tools/$slug': typeof ArToolsSlugRoute
  '/es/tools/$slug': typeof EsToolsSlugRoute
  '/fr/tools/$slug': typeof FrToolsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/background-remover'
    | '/blog.rss.xml'
    | '/changelog'
    | '/contact'
    | '/jpg-to-webp'
    | '/passport-photo-maker'
    | '/pdf-translator'
    | '/privacy'
    | '/terms'
    | '/ai-prompts/$slug'
    | '/blog/$slug'
    | '/tools/$slug'
    | '/vs/$competitor'
    | '/ai-prompts/'
    | '/ar/'
    | '/blog/'
    | '/es/'
    | '/fr/'
    | '/vs/'
    | '/ar/tools/$slug'
    | '/es/tools/$slug'
    | '/fr/tools/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/background-remover'
    | '/blog.rss.xml'
    | '/changelog'
    | '/contact'
    | '/jpg-to-webp'
    | '/passport-photo-maker'
    | '/pdf-translator'
    | '/privacy'
    | '/terms'
    | '/ai-prompts/$slug'
    | '/blog/$slug'
    | '/tools/$slug'
    | '/vs/$competitor'
    | '/ai-prompts'
    | '/ar'
    | '/blog'
    | '/es'
    | '/fr'
    | '/vs'
    | '/ar/tools/$slug'
    | '/es/tools/$slug'
    | '/fr/tools/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/background-remover'
    | '/blog.rss.xml'
    | '/changelog'
    | '/contact'
    | '/jpg-to-webp'
    | '/passport-photo-maker'
    | '/pdf-translator'
    | '/privacy'
    | '/terms'
    | '/ai-prompts/$slug'
    | '/blog/$slug'
    | '/tools/$slug'
    | '/vs/$competitor'
    | '/ai-prompts/'
    | '/ar/'
    | '/blog/'
    | '/es/'
    | '/fr/'
    | '/vs/'
    | '/ar/tools/$slug'
    | '/es/tools/$slug'
    | '/fr/tools/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BackgroundRemoverRoute: typeof BackgroundRemoverRoute
  BlogDotrssDotxmlRoute: typeof BlogDotrssDotxmlRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  JpgToWebpRoute: typeof JpgToWebpRoute
  PassportPhotoMakerRoute: typeof PassportPhotoMakerRoute
  PdfTranslatorRoute: typeof PdfTranslatorRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AiPromptsSlugRoute: typeof AiPromptsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  VsCompetitorRoute: typeof VsCompetitorRoute
  AiPromptsIndexRoute: typeof AiPromptsIndexRoute
  ArIndexRoute: typeof ArIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EsIndexRoute: typeof EsIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  VsIndexRoute: typeof VsIndexRoute
  ArToolsSlugRoute: typeof ArToolsSlugRoute
  EsToolsSlugRoute: typeof EsToolsSlugRoute
  FrToolsSlugRoute: typeof FrToolsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-translator': {
      id: '/pdf-translator'
      path: '/pdf-translator'
      fullPath: '/pdf-translator'
      preLoaderRoute: typeof PdfTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-photo-maker': {
      id: '/passport-photo-maker'
      path: '/passport-photo-maker'
      fullPath: '/passport-photo-maker'
      preLoaderRoute: typeof PassportPhotoMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-webp': {
      id: '/jpg-to-webp'
      path: '/jpg-to-webp'
      fullPath: '/jpg-to-webp'
      preLoaderRoute: typeof JpgToWebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog.rss.xml': {
      id: '/blog.rss.xml'
      path: '/blog.rss.xml'
      fullPath: '/blog.rss.xml'
      preLoaderRoute: typeof BlogDotrssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-remover': {
      id: '/background-remover'
      path: '/background-remover'
      fullPath: '/background-remover'
      preLoaderRoute: typeof BackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/': {
      id: '/vs/'
      path: '/vs'
      fullPath: '/vs/'
      preLoaderRoute: typeof VsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/ar'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-prompts/': {
      id: '/ai-prompts/'
      path: '/ai-prompts'
      fullPath: '/ai-prompts/'
      preLoaderRoute: typeof AiPromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$competitor': {
      id: '/vs/$competitor'
      path: '/vs/$competitor'
      fullPath: '/vs/$competitor'
      preLoaderRoute: typeof VsCompetitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-prompts/$slug': {
      id: '/ai-prompts/$slug'
      path: '/ai-prompts/$slug'
      fullPath: '/ai-prompts/$slug'
      preLoaderRoute: typeof AiPromptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/tools/$slug': {
      id: '/fr/tools/$slug'
      path: '/fr/tools/$slug'
      fullPath: '/fr/tools/$slug'
      preLoaderRoute: typeof FrToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/tools/$slug': {
      id: '/es/tools/$slug'
      path: '/es/tools/$slug'
      fullPath: '/es/tools/$slug'
      preLoaderRoute: typeof EsToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/tools/$slug': {
      id: '/ar/tools/$slug'
      path: '/ar/tools/$slug'
      fullPath: '/ar/tools/$slug'
      preLoaderRoute: typeof ArToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BackgroundRemoverRoute: BackgroundRemoverRoute,
  BlogDotrssDotxmlRoute: BlogDotrssDotxmlRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  JpgToWebpRoute: JpgToWebpRoute,
  PassportPhotoMakerRoute: PassportPhotoMakerRoute,
  PdfTranslatorRoute: PdfTranslatorRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AiPromptsSlugRoute: AiPromptsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  VsCompetitorRoute: VsCompetitorRoute,
  AiPromptsIndexRoute: AiPromptsIndexRoute,
  ArIndexRoute: ArIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  EsIndexRoute: EsIndexRoute,
  FrIndexRoute: FrIndexRoute,
  VsIndexRoute: VsIndexRoute,
  ArToolsSlugRoute: ArToolsSlugRoute,
  EsToolsSlugRoute: EsToolsSlugRoute,
  FrToolsSlugRoute: FrToolsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
